### ISSUE TITLE
can you provide the training logs / wandb curve

### ISSUE THREAD

**Issue by wangzheallen** [TIGER-AI-Lab/VideoScore#3]
Specifically the "bash scripts/train_idefics2_video_eval.sh"

**Comment by wenhuchen** [comment]
@jdf-prog

**Comment by hexuan21** [comment]
Hi the Wandb training curves are here: 
[VideoScore](https://api.wandb.ai/links/xuanhe/ptohlfcx)
[VideoScore-anno-only](https://api.wandb.ai/links/xuanhe/4vs5k0cq)
